### ISSUE TITLE
请问一下 iOS运行报错是什么原因

### ISSUE THREAD

**Issue by qllqll** [liuweilyy/easy_contact_picker#2]
Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "easy_contact_picker":
      In Podfile:
        easy_contact_picker (from `.symlinks/plugins/easy_contact_picker/ios`)

    Specs satisfying the `easy_contact_picker (from `.symlinks/plugins/easy_contact_picker/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by ampersanda** [comment]
Why is this closed? How this problem solved?

**Comment by liuweilyy** [comment]
报什么错呢，权限都添加了吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ampersanda <notifications@github.com&gt;
发送时间: 2020年2月18日 18:55
收件人: liuweilyy/easy_contact_picker <easy_contact_picker@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[liuweilyy/easy_contact_picker] 请问一下 iOS运行报错是什么原因 (#2)




Why is this closed? How this problem solved?

**Comment by ampersanda** [comment]
I solve this problem by change the iOS OS requirement from 8.0 to 10.0
